/** @type {import('tailwindcss').Config} */
// const plugin = require("tailwindcss/plugin");

module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    screens: {
      xs: "350px",
      sm: "600px",
      md: "750px",
      lg: "1000px",
      lgm: "1200px",
      xl: "1281px",
      "2xl": "1536px",
    },
    extend: {},
    colors: {
      brand_primary: "#FFF44F",
      light_brand_primary: "#FFFEE2",
      dark_brand_primary: "#FF9900",
      brand_secondary: "#1C1C1C",
      black: "#000000",
      white: "#ffffff",
      green: "#08CF5A",
      error: "#DF3939",
      error_tint: "#FAE0E0",
      success: "#23CE6B",
      success_fade: "#F2FDF6",
      success_900: "#106032",
      warning: "#F59E0B",
      transparent: "#00000000",
      neutral_stroke_1: "#DFE2E2",
      neutral_disabled: "#F2F3F3",
      neutral_stroke_2: "#ECEEEE",
      border_stroke_1: "#000000",
      border_stroke_2: "#6E6E6E",
    },
    fontSize: {
      6: "0.375rem",
      10: "0.625rem",
      12: "0.75rem",
      14: "0.875rem",
      16: "1rem",
      18: "1.125rem",
      20: "1.25rem",
      22: "1.375rem",
      24: "1.5rem",
      25: "1.563rem",
      28: "1.75rem",
      32: "2rem",
      40: "2.5rem",
      60: "3.75rem",
    },
    fontFamily: {
      aeroMatics_r: ["aeroMatics_r", "sans-serif"],
      aileron_l: ["aileron_l", "sans-serif"],
      aileron_r: ["aileron_r", "sans-serif"],
      aileron_sb: ["aileron_sb", "sans-serif"],
      aileron_b: ["aileron_b", "sans-serif"],
      albra_sans_l: ["albra_sans_l", "sans-serif"],
      albra_sans_r: ["albra_sans_r", "sans-serif"],
      albra_sans_m: ["albra_sans_m", "sans-serif"],
      albra_sans_b: ["albra_sans_b", "sans-serif"],
      albra_sans_sb: ["albra_sans_sb", "sans-serif"],
    },
  },
  plugins: [],
};
